
package proxy;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://WS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param arg0
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://WS/", className = "proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://WS/", className = "proxy.GetCompteResponse")
    @Action(input = "http://WS/BanqueService/getCompteRequest", output = "http://WS/BanqueService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConvertionEuroToDh")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConvertionEuroToDh", targetNamespace = "http://WS/", className = "proxy.ConvertionEuroToDh")
    @ResponseWrapper(localName = "ConvertionEuroToDhResponse", targetNamespace = "http://WS/", className = "proxy.ConvertionEuroToDhResponse")
    @Action(input = "http://WS/BanqueService/ConvertionEuroToDhRequest", output = "http://WS/BanqueService/ConvertionEuroToDhResponse")
    public double convertionEuroToDh(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listCompte", targetNamespace = "http://WS/", className = "proxy.ListCompte")
    @ResponseWrapper(localName = "listCompteResponse", targetNamespace = "http://WS/", className = "proxy.ListCompteResponse")
    @Action(input = "http://WS/BanqueService/listCompteRequest", output = "http://WS/BanqueService/listCompteResponse")
    public List<Compte> listCompte();

}
